server:
    port: 8051
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    security:
        user:
            name: admin
            password: 1234
    application:
        name: flix-streaming
    datasource:
        url: jdbc:postgresql://postgres_streaming:5432/flix
        username: dydwls140
        password: "@astems1027"
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        hibernate:
            # ddl-auto: update # 애플리케이션 시작 시 데이터베이스 스키마를 자동 업데이트합니다.
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    sql:
        init:
            mode: never
    devtools:
        restart:
            enabled: true
