spring:
    application:
        name: streaming
    config:
        import: configserver:http://${CONFIG_HOST}:${CONFIG_PORT}
    cloud:
        config:
            profile: ${SPRING_PROFILES_ACTIVE} # 사용할 프로필
            label: main # Git 브랜치 (기본값: main)

