# 공통 설정
spring:
    application:
        name: streaming
    profiles:
        active: local # 기본 프로필 설정

app:
    video:
        dir: src/main/resources/videos/

---
# local 환경 설정
spring:
    config:
        activate:
            on-profile: local
        import: configserver:http://${CONFIG_LOCAL_HOST}:${CONFIG_LOCAL_PORT}
    cloud:
        config:
            profile: local
            label: main

---
# dev 환경 설정
spring:
    config:
        activate:
            on-profile: dev
        import: configserver:http://${CONFIG_DEV_HOST:dev-host}:${CONFIG_DEV_PORT}
    cloud:
        config:
            profile: dev
            label: main

---
# prod 환경 설정
spring:
    config:
        activate:
            on-profile: prod
        import: configserver:http://${CONFIG_PROD_HOST:prod-host}:${CONFIG_PROD_PORT}
    cloud:
        config:
            profile: prod
            label: main
